name: Docker Image

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - next
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "next"

# Sets permissions of the GITHUB_TOKEN
permissions:
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            {%raw%}ghcr.io/${{ github.repository}}{%endraw%}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            {%raw%}type=semver,pattern={{version}}{%endraw%}
            {%raw%}type=semver,pattern={{major}}.{{minor}}{%endraw%}
            {%raw%}type=semver,pattern={{major}}{%endraw%}
            type=sha
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: {%raw%}${{ github.repository_owner }}{%endraw%}
          password: {%raw%}${{ secrets.GITHUB_TOKEN }}{%endraw%}
      - name: Write pip config
        run: |
          touch pip.conf

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          provenance: false
          tags: {%raw%}${{ steps.meta.outputs.tags }}{%endraw%}
          labels: {%raw%}${{ steps.meta.outputs.labels }}{%endraw%}
          secret-files: |
            "pip-config=./pip.conf"
