pool:
  vmImage: "ubuntu-latest"

trigger:
  tags:
    include:
      - "*"

variables:
  artifactFeed: quara-project

jobs:
  - job: Publish release
    steps:
      - checkout: self

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.8"

      - script: |
          python -m pip install --user invoke twine
          python scripts/install.py -e build,docs
        displayName: Install dependencies

      - script: |
          python -m invoke build --docs
          cd dist/
          zip -r documentation.zip documentation
        displayName: Build package

      - task: TwineAuthenticate@0
        inputs:
          artifactFeeds: "$(artifactFeed)"

      - script: |
          echo -e "Publishing on feed $(feed.name) using configuration file $(PYPIRC_PATH)"
          twine upload -r $(feed.name) --config-file $(PYPIRC_PATH) dist/*
        displayName: Publish software

      # Deploy Azure Static Web App v0
      # - task: AzureStaticWebApp@0
      #   inputs:
      #     output_location: dist/documentation
      #     skip_app_build: true
      #     is_static_export: true
      #     verbose: true
      #   displayName: Publish documentation to Azure Static Web App
