---
pool:
  vmImage: "ubuntu-latest"

# Trigger using Branch Policies. DO NOT use azure repos triggers
trigger: none

variables:
  # Update sonar cloud endpoint name if required
  sonarCloudEndpointName: "SC"
  sonarCloudOrganization: "{{ cookiecutter.sonar_organization }}"
  sonarCloudProjectKey: "{{ cookiecutter.sonar_key }}"
  sonarCloudProjectName: "{{ cookiecutter.project_name }}"

stages:
  - stage: Continuous Integration
    jobs:
      - job: Lint and test
        strategy:
          matrix:
            PYTHON_38:
              PYTHON_VERSION: "3.8"
            PYTHON_39:
              PYTHON_VERSION: "3.9"
            PYTHON_310:
              PYTHON_VERSION: "3.10"
            PYTHON_311:
              PYTHON_VERSION: "3.11"
        steps:
          - checkout: self

          - task: UsePythonVersion@0
            inputs:
              versionSpec: $(PYTHON_VERSION)

          - script: python3 scripts/install.py -e dev
            displayName: Install project and dependencies

          - script: ./.venv/bin/inv lint
            displayName: Lint with flake8

          - script: ./.venv/bin/inv check --include-tests
            displayName: Lint with mypy

          - script: ./.venv/bin/inv check --coverage
            displayName: Test with pytest

          # Only test result for Python 3.11 will be available
          # If you use multiple publish code coverage tasks in the pipeline, the summary and report is shown for the last task. Any previously uploaded data is ignored.
          # Reference: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v1?view=azure-pipelines#is-code-coverage-data-merged-when-multiple-files-are-provided-as-input-to-the-task-or-multiple-tasks-are-used-in-the-pipeline
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "$(System.DefaultWorkingDirectory)/**/junit*.xml"
            displayName: Publish tests results

          # Only code coverage for Python 3.11 will be available
          # If you use multiple publish code coverage tasks in the pipeline, the summary and report is shown for the last task. Any previously uploaded data is ignored.
          # Reference: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-code-coverage-results-v1?view=azure-pipelines#is-code-coverage-data-merged-when-multiple-files-are-provided-as-input-to-the-task-or-multiple-tasks-are-used-in-the-pipeline
          - task: PublishCodeCoverageResults@1
            condition: succeededOrFailed()
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/cov.xml"
              reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage-report"
            displayName: Publish code coverage

      - job: Run SonarCloud analysis
        steps:
          - checkout: self

          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: "$(sonarCloudEndpointName)"
              organization: "$(sonarCloudOrganization)"
              scannerMode: "CLI"
              configMode: "manual"
              cliProjectKey: "$(sonarCloudProjectKey)"
              cliProjectName: "$(sonarCloudProjectName)"
              cliSources: "src"
              extraProperties: |
                sonar.verbose=true
            displayName: Prepare SonarCloud analysis

          - task: SonarCloudAnalyze@1
            displayName: Run SonarCloud analysis

          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: "300"
            displayName: Wait for SnarCloud to publish result on the Pipeline build summary
