---
pool:
  vmImage: "ubuntu-latest"

# Only trigger automaticallly on stable branch
trigger:
  - main

steps:
  - checkout: self
    persistCredentials: true

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
  - task: NodeTool@0
    inputs:
      versionSpec: "18.x"

  - script: |
      npm i -g \
        semantic-release \
        @semantic-release/commit-analyzer \
        @semantic-release/changelog \
        @semantic-release/exec \
        conventional-changelog-conventionalcommits
    displayName: Install semantic release

  - script: |
      semantic-release --debug
    displayName: Execute semantic release
