name: Continuous Integration

on:
  push:
    branches: [next, main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [next, main]

jobs:
  test:
    name: Lint and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure git
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "test"

      - name: Run unit tests
        run: pytest -s tests/
